feat: add srcset generation method
imgix/imgix-java pull request #32
Opened 2019-09-12 00:28 UTC by sherwinski

This PR creates a new class method in `URLBuilder` that will generate the value of a `srcset` attribute, part of an `<img>` HTML element. `createSrcSet()` takes a `path` and `params` argument similar to `createURL()`, and can return two types of `srcset` formats.

**Srcset Width-Pairs**
The first format creates `srcset` width-pairs, which allows for responsive size switching based on the current size of the browser viewport. `createSrcSet()` will return the `srcset` in this format by default (when only given a `path`) unless specific conditions are true, which is covered in the second format. The following is an example of a width-pair `srcset`:

```java
URLBuilder ub = new URLBuilder("test.imgix.net", true, "", false);
System.out.println(ub.createSrcSet("bridge.png"));
```
which should return the following `String` (collapsed for brevity):
```html
https://test.imgix.net/bridge.png?w=100 100w,
https://test.imgix.net/bridge.png?w=116 116w,
https://test.imgix.net/bridge.png?w=134 134w,
											...
https://test.imgix.net/bridge.png?w=7400 7400w,
https://test.imgix.net/bridge.png?w=8192 8192w
```
Notice that a `w=` parameter is automatically inserted for each entry in the `srcset` list. This is required in order for the element to properly display the correctly-sized image corresponding to the viewport's width.

**Device Pixel Ratio (DPR) Srcset**

For more information on `srcset`, building responsive images, and resolution switching:
- [Responsive images - MDN](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images)
- [Srcset and Sizes - Eric Portis](https://ericportis.com/posts/2014/srcset-sizes/)

2019-09-18 21:11 UTC, nickypy approved these changes

2019-09-19 00:19 UTC, jayeb requested changes
A few small issues and nitpicks, but this is pretty close.

2019-09-19 00:19 UTC, jayeb commented on src/main/java/com/imgix/URLBuilder.java
> +		return srcset.substring(0,srcset.length()-2);
```suggestion
		return srcset.substring(0, srcset.length() - 2);
```

2019-09-19 00:19 UTC, jayeb commented on src/main/java/com/imgix/URLBuilder.java
> +		return srcset.substring(0,srcset.length()-2);
```suggestion
		return srcset.substring(0, srcset.length() - 2);
```

2019-09-19 00:19 UTC, jayeb commented on src/main/java/com/imgix/URLBuilder.java
> +
```suggestion
```

2019-09-19 00:19 UTC, jayeb commented on src/main/java/com/imgix/URLBuilder.java
> +		while (prev <= MAX_SIZE) {
```suggestion
		while (prev < MAX_SIZE) {
```

2019-09-19 00:19 UTC, jayeb commented on src/main/java/com/imgix/URLBuilder.java
> +			resolutions.add((int)(2 * Math.round(prev/2)));
```suggestion
			resolutions.add((int)(2 * Math.round(prev / 2)));
```

2019-09-19 00:19 UTC, jayeb commented on src/main/java/com/imgix/URLBuilder.java
> +			resolutions.add((int)(2 * Math.round(prev/2)));
Also, I think I'd prefer to see this line broken up.

```java
int roundedPrev = 2 * Math.round(prev / 2);
resolutions.add(roundedPrev);
```

2019-09-19 20:12 UTC, jayeb approved these changes

2019-09-19 20:14 UTC, merged