chore: add pull request template and CODEOWNERS
imgix/imgix-java pull request #59
Opened 2020-07-31 22:57 UTC by sherwinski

2020-08-03 23:28 UTC, ericdeansanchez requested changes

2020-08-03 23:28 UTC, ericdeansanchez commented on .github/pull_request_template.md
> +- [ ] If this is a big feature with breaking changes, consider [opening an issue][issues] to discuss first. This is completely up to you, but please keep in mind that your PR might not be accepted.
Is this a typo
```
[opening an issue][issues]
```
or does this actually resolve to anything?

2020-08-03 23:45 UTC, sherwinski commented on .github/pull_request_template.md
> +- [ ] If this is a big feature with breaking changes, consider [opening an issue][issues] to discuss first. This is completely up to you, but please keep in mind that your PR might not be accepted.
🤦 it definitely does not

2020-08-05 01:22 UTC, ericdeansanchez approved these changes

2020-08-05 01:25 UTC, merged